description = "This is a configuration file for flint, the filesystem linter. More information here: https://github.com/z0mbie42/flint"
default_severity = "warning"
error_exit_code = 1
warning_exit_code = 0
match_format = "blob"
ignore_files = [".*", "vendor", "LICENSE", "README.md", "CHANGELOG.md", "_build/Dockerfile", "Makefile"]
ignore_directories = [".*", "vendor", "_build", "_docs"]

[rules]
  [rules."dir/no_dot"]
  [rules."file/lower_case_ext"]
  [rules."file/no_multi_ext"]
  [rules.no_empty_name]
  [rules.no_leading_underscores]
  [rules.no_trailing_underscores]
  [rules.no_whitespaces]
  [rules.snake_case]
    severity = "error"
